name: Run Node App and Curl Localhost

on:
  push:
  workflow_dispatch:

jobs:
  run-app:
    runs-on: ubuntu-latest
    permissions:
      issues: write 

    steps:
      - name: Checkout repository
        uses: actions/checkout@v6

      - name: Install Node.js
        uses: actions/setup-node@v6
        with:
          node-version: 24

      - name: Install dependencies
        run: npm install

      - name: Start app
        run: |
          npm start &
          sleep 10

      - name: Run ZAP full scan
        uses: zaproxy/action-baseline@v0.15.0
        with:
          target: 'http://localhost:3000'
          allow_issue_writing: false